name: Deploy

concurrency: 
  group: deploy

on:
  push:
  workflow_dispatch:

env:
  PROJECT_NAME: libreoj-frontend
  PACKAGE_NAME: "@lyrio/ui"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node_modules
      uses: actions/cache@v2
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock', 'patches/**') }}
        restore-keys: ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --production --frozen-lockfile
    - name: Download files
      run: yarn ts-node-esm download.ts ${{ env.PACKAGE_NAME }} ./dist
    - name: Deploy to Static CDN
      uses: AyaInfra/StaticCDNDeploy@main
      with:
        deploy-credentials: ${{ secrets.STATIC_CDN_CREDENTIALS }}
        local-path: dist
        remote-path: libreoj-frontend
